### ISSUE TITLE
Consider using Cloudflare pages to host this

### ISSUE THREAD

**Issue by Gocnak** [StrataSource/Wiki#12]
Cloudflare pages is really awesome and has preview builds for non-main branches that allow previewing changes before they go live.

**Comment by kittymatthew** [comment]
Yes - I can second this - this would make hosting and editing the wiki a lot more enjoyable!

**Comment by EchoesForeAndAft** [comment]
Some useful docs:

* [Migrating a Jekyll-based site from GitHub Pages](https://developers.cloudflare.com/pages/migrations/migrating-jekyll-from-github-pages)
* [GitHub integration](https://developers.cloudflare.com/pages/platform/github-integration)

**Comment by ozxybox** [comment]
We have moved to cloudflare pages!
