### ISSUE TITLE
Strata Source's documentation articles are duplicated.

### ISSUE THREAD

**Issue by aag8a** [StrataSource/Wiki#45]
Articles in Strata Source's docs are duplicated, either they are in Reference, VScript or Panorama.
![img-2024-01-08-11-20-04](https://github.com/StrataSource/Wiki/assets/72987745/9d026ea4-70fb-4a9e-9f00-723272522128)
![img-2024-01-08-11-21-19](https://github.com/StrataSource/Wiki/assets/72987745/fc25a613-1131-471f-94e2-c08863258e71)
![img-2024-01-08-11-21-30](https://github.com/StrataSource/Wiki/assets/72987745/88a353ac-cb29-4105-a2a0-861292ca65ff)

**Comment by ozxybox** [comment]
This has now been fixed!
