### ISSUE TITLE
Merge over the semi-old wiki pages

### ISSUE THREAD

**Issue by ozxybox** [StrataSource/Wiki#53]
I learned today that we had an in between wiki at some point! There's a few pages on here that seemingly never got transferred over to the new setup, that got transferred to this setup. 

Let's get what we don't already have moved over and close down the duplicate.

https://github.com/StrataSource/Portal-2-Community-Edition/wiki/

**Comment by JJL772** [comment]
This wiki was used in between our original wiki and current one. Was a bit easier to edit

**Comment by ozxybox** [comment]
Ah okay, I had started to suspect that might’ve been the case. Only semi-old then!

**Comment by JJL772** [comment]
Amazing how much time we have spent on wiki stuff haha

**Comment by ozxybox** [comment]
Closed by PR #54
